# Generated by Django 3.2.12 on 2022-04-01 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0051_auto_20220330_0812'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attributespec',
            unique_together={('label', 'id', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('task', 'id', 'name')},
        ),
    ]
